hotwax/fulfillment-pwa

changelogs/unreleased/-1x0efxp.yml
src/theme/variables.css

- Added `overflow-x` on the filters class

Improved: the overflow property for filters to only scroll it in x-axis(#1x0efxp)

---

src/views/timezone-modal.vue

Closes #
:- Worked on improving the code to use keyUp event for enter button instead of 'ionInput' for timeZone search.

Improved: code to use enter instead of input for Timezone search (#2cj8zmd).

---

src/store/modules/product/actions.ts

Fixed: Used console.error instead of console.log

---

src/store/modules/stock/actions.ts

Implemented: support to handle the case when checkInventory api exceeds the limit(#85zrx65t8)

---

src/views/Settings.vue

On login, api calls to get the count of inProgress and outstanding orders is being made, as after login we set the facility and eComStore that results in calling the apis.
Closes #
Added condition to check for values in state and current selected value and if both are same not making api calls.

Fixed: issue of unwanted api calls after login, due to change in facility and productStore

---

src/store/modules/order/actions.ts
src/views/InProgress.vue

When switching from Ready to pack to Report an issue and then reverting, the save button doesn't reflect the change and still rejects items
Closes #146 

Fixed: Issue with report an issue on in progress page (#146)

---

src/components/Menu.vue
src/views/UploadImportOrders.vue

Closes #
- Updated column labels for import CSV
- Removed unused imports
- Fixed issue to regenerate mapping when uploaded file is changed

Improved: column labels for import functionality and removed some unused imports

---

src/components/Menu.vue

Closes #137 
- Removed a watcher from the menu component that checks for route changes
- Defined a computed property to find the correct index in the menu list
- Added an entry in the menu component pages to list all the child routes those are not listed in the menu for a specific parent route, using which we have enabled the correct menu in the UI.
https://github.com/hotwax/fulfillment-pwa/assets/41404838/a4556d47-6807-466a-8fc7-21425057a3eb

Fixed: issue of menu not being enabled for the correct page when using the back button(#137)

---

src/store/modules/order/actions.ts
src/views/Completed.vue

Closes #162 
Removed passing queryFields params when preparing the query, as when the queryFields are not passed by default searching works on `productId productName virtualProductName orderId productSku customerId customerName search_orderIdentifications goodIdentifications`
After:

Fixed: searching on some fields not working on open orders page(#162)

---

src/views/DownloadPackedOrders.vue

Closes #160 
Added a check, that if there are no fields available, then disable the select all button.
After:

Fixed: select all button to be disabled when there are no fields available for mapping(160)

---

src/store/modules/order/actions.ts
src/views/Completed.vue
src/views/InProgress.vue

Closes #176
- Added spinner so that the user knows that some process is going on in background.
- Added the spinner in the end where the button is having some label, and if the button is having an icon then replacing the button with the spinner

Implemented: support to display a spinner on document printing buttons(#176)

---

src/views/AssignPickerModal.vue

Closes #183 
Helps in identifying the picker easily when pickers are sharing the same name.
Before:
After:

Implemented: support to display the picker id below picker name in the assign picker modal on open page(#183)

---

src/store/modules/order/actions.ts
src/views/InProgress.vue

Closes #198 
In the current scenario, when a user clicks the add box button multiple times, multiple boxes gets added with the same package name, resulting in wrong user experience. So created a flag `isAddingBox` on order level to know whether the box adding is in-process or completed and not make furthur api calls for adding the box untill the previous call is not completed.

Fixed: issue of same package being added when clicking add box button multiple times(#198)

---

src/views/InProgress.vue

Fixed: issue of multiple shipmentIds being passed even when the shipments are not used

---

src/store/modules/order/actions.ts

Closes #218
If check in find in progress order action and find completed order action
that if orders are not found then do not fetch additional information

Implemented: a check in findOrders actions in progress and completed that if no orders are found then do not fetch additional information

---

src/locales/en.json
src/locales/es.json
src/services/OrderService.ts
src/utils/index.ts
src/views/InProgress.vue

Closes #254
Implemented the following - 
- handled error while redirecting to new tab ( Now showing toast to user that browser pop up is blocked so unable to open the document )
- changes in showToast function of utils so that it can be used with other options also
- changes in progress view as showtoast function changed ( if there are more args in showToast now passing them as object with options) 
- Show toast when unable to open order documents when browser pop ups are blocked.
- Show toast which can be dismissed by the user when packing in progress order.

Implemented: toast for Blocked Pop-Ups when Generating Order Documents (#254)

---

src/locales/en.json
src/locales/es.json
src/services/StockService.ts
src/store/index.ts
src/store/modules/stock/StockState.ts
src/store/modules/stock/UtilState.ts
src/store/modules/stock/actions.ts
src/store/modules/stock/getters.ts
src/store/modules/stock/index.ts
src/store/modules/stock/mutation-types.ts
src/store/modules/stock/mutations.ts
src/views/Completed.vue
src/views/InProgress.vue
src/views/OpenOrders.vue

Closes #182 
- Go to any of the open, inProgress or completed page
- Click on cube icon to fetch the stock
- Verify that the stock is visible and if not fetched due to an error in api then toast is displayed.
After:
When stock for product is not yet fetched:
When stock for a product is available:

Implemented: support to show product QOH on order card(#182)

---

src/store/modules/user/actions.ts

Closes #
Currently, in some cases the logout api makes an internal redirection, and thus we are unable to parse the resp which in turn halts the logout process, so fixed this case by wrapping the parsing logic of resp in try-catch block, so if in any case parsing fails the user still gets logged out of the app.

Fixed: issue of user unable to logout from the app

---

src/store/modules/order/actions.ts
src/views/AssignPickerModal.vue
src/views/OpenOrders.vue

Improved: open order structure for handling

---

src/store/modules/order/actions.ts
src/store/modules/stock/actions.ts
src/store/modules/stock/getters.ts
src/store/modules/stock/mutations.ts
src/views/OrderDetail.vue

Closes #
- Removed code to filter the STOREPICKUP shipGroups, as we can display storePickup information as well in additional details.
- Removed support to exclude storePickup shipGroups from additional information
- Added support to store product stock by facility in the format: `{ productId: { facility1: stock, facility2: stock } }`

Improved: code to have support for storing stock by facility(#313)

---

src/store/modules/order/actions.ts
src/views/OrderDetail.vue

Closes #
Implemented: Print Picklist PDF from order detail page.

Implemented: Print Picklist PDF from order detail page.

---

src/utils/order.ts

When fetching the status for related shipGroups, only the keys check is honored and not the values are honored for checking status
Closes #
Instead of ORing on keys and value checks, changed the operator to `and`.

Fixed: case to honor params when checking for shipGroup status on details page

---

src/store/modules/user/actions.ts

Closes #
As we have updated the keys for locale from `en` to `en-US` etc, so when updating the env entry the old keys are also available in the localStorage thus resulting in duplicate records for languages. So added support to reset the locale records on logout.

Fixed: issue of duplicate records of locale entry on settings page

---

src/services/OrderService.ts
src/store/modules/order/actions.ts
src/utils/index.ts
src/views/ShippingDetails.vue

Implemented: show customer phone number on the order details page (#348)

---

src/locales/en.json
src/locales/es.json
src/views/Completed.vue
src/views/OrderDetail.vue

Fixed: case to display shipping label button always on completed page and show an error toast when having missing shipment method configuration

---

src/components/ShippingLabelErrorModal.vue

Closes #380
Implemented copy button and text wrap in shipping label error message modal.

Implemented: copy utility and text wrap in shippingLabelError modal (#380)

---

src/views/Completed.vue

Closes #389
When we complete an order, the result size filter selected by user gets reset to default. Hence fixed this issue for not allowing it to reset.

Fixed: result size filter reset when completing an order issue (389)

---

src/locales/en.json
src/views/Completed.vue
src/views/InProgress.vue
src/views/OpenOrders.vue

Closes #404 
Updated the Searchbar text label from 'Search' to 'Search orders'.
Before: 
After: 

Fixed: the ion-searchbar placeholder as 'search' to 'search orders'

---

src/locales/en.json
src/views/timezone-modal.vue

…ata is being fetched
Closes #
I have incorporated a spinner in the TimeZoneModal to provide users with a visual cue, allowing them to easily discern when data is being fetched. This not only enhances the user experience but also ensures that users can perceive the ongoing data retrieval process

Implemented: Spinner in Timezone modal such that users will see that data is being fetched

---

src/components/CreateRejectionReasonModal.vue

Closes #
Removed double line from the create rejection reason modal in ID input.
Before
After

Fixed: remove double line from the id input in create rejection reason modal

---

src/views/OrderDetail.vue

Related Issue #470
Fixed check stock showing in the middle of the order item.
Before
After

Fixed: check stock button coming in middle due to only 2 items in order-item div (#470)

---

src/views/RejectionReasons.vue

Related Issue #487
Fixed fav icon overlapping the last reason in rejection reasons page
Before 
After

Fixed: fav icon overlapping the last reason in rejection reasons page (#487)

---

src/views/RejectionReasons.vue

Related Issue #466
Fixed - 
- Toast not showing up again on reordering reasons after saving once.
- Alert coming even after saving toast on changing route.

Fixed: toast remains active once saving rejection reasons order (#466)

---

src/views/Completed.vue
src/views/InProgress.vue
src/views/OpenOrders.vue
src/views/TransferOrders.vue

https://github.com/hotwax/dxp-components/issues/289
In Ionic 7.6.0, an issue was fixed that caused infinite scroll to trigger when quickly scrolling or when items had not filled the entire page. This issue resulted in infinite scroll problems when used with search functionality. A key was added to the infinite scroll to trigger a re-render when the keyword is changed.

Fixed: infinite scroll issue when used with searchbar(dxp-289) 

---

src/views/Completed.vue
src/views/InProgress.vue
src/views/OpenOrders.vue
src/views/TransferOrders.vue

https://github.com/hotwax/dxp-components/issues/289
Removed the logic to re-render the infinite-scroll on queryString check that has been added in the previous PR.
Added a variable to check whether the scrolling can be enabled or not whenever users lands on the list page. For this, we have determined the height of the content part scroll and infiniteScroll component and if the height is less than 0 then only enabling the infinite-scroll component
Removed disabled as once the infiniteScroll is disabled it does not gets enabled again, hence removed the disabled property and instead used v-show to enable/disable infinite scroll.

Fixed: infinite scroll issue when used with searchbar(dxp-289)

---

src/App.vue
src/store/modules/user/actions.ts

Related Issue #504 
When making api call to fetch identification for products it gets failed as unauthorized as the token is not set till the api call. As the api fails, it clears the oms-url and as the apps flow does not break for this api failure some other apis gets called with the app's url instead of oms-url.
Moved the logic to update the token to handle the api failure case so that endpoints will not be prepared for app. Also added a check on app's mount that the identification method should only be called if we have a token available.

Fixed: case of api failure as the endpoints using app's domain instead of oms domain(#504)

---

src/store/modules/carrier/actions.ts
src/views/CarrierDetail.vue

Closes #
Fixed: Product store shipment method association logic to persist the state of each product store (#493).

Fixed: Product store shipment method association logic to persist the state of each product store (#493).

---

src/views/InProgress.vue
src/views/OpenOrders.vue

#512 
- Added snippet to `dismiss` the alert box after rejecting.
- Added `loader` after dismissing the alert until the `API` completes."

Fixed: On reject, the alert will close, and the loader will be displayed(#512)

---

src/components/TransferOrderItem.vue

#557 
- Changed the position of `pickedQuantity` (`ref`)  from ion-item to ion-input.

Fixed: change the position of the 'ref' in ion-input(#557)

---

src/views/RejectionReasons.vue

Related Issue #553
Used default cursor instead of using pointer cursor on the rejection reasons list item since the items are not clickable.

Improved: used default cursor on the rejection reasons list item since not clickable (#553)
