hotwax/fulfillment-pwa

- changelogs/unreleased/-1x0eg0t.yml
- src/views/EditPackagingModal.vue
> Added: the add box button on the edit packaging modal(#1x0eg0t)

- changelogs/unreleased/-21aqct8.yml
- src/views/Completed.vue
- src/views/InProgress.vue
- src/views/Login.vue
- src/views/OpenOrders.vue
- src/views/Settings.vue
- src/views/UploadCsv.vue
> Removed fullscreen=true from ion-content of all pages(#21aqct8)

- src/views/Settings.vue
> Added time-outline icon for timezone(#25k73ff)

- src/App.vue
- src/store/modules/user/actions.ts
> Removed timezone mismatch alert on login(2893rqm)

- src/views/timezone-modal.vue
Closes #
:- Worked on improving the code to assign input field to instance variable for searchbar.
Because when performing any action on search with enter key, the value of instance variable is set after the action is performed due to which wrong data is passed to API.
> Improved: code to assign input field to instance variable for searchbar (#2cj8nc4).

- README.md
> Updated contribution guideline point(#2r0kmb3)

- package-lock.json
- package.json
> Upgraded to ionic 6.2(#2w9wz26)

- capacitor.config.json
- ionic.config.json
- package-lock.json
- package.json
> Improved: oms api package version to latest release and updated the app name

- package-lock.json
- package.json
- release-notes.md
> Updated: app version and release notes for major release(v1.0.0)

- src/App.vue
- src/adapter/index.ts
> Fixed: issue of login navigation failed on token expire(#85zruuj2w)

- package-lock.json
- package.json
- release-notes.md
> Updated: app version and release notes for minor release(v1.1.0)

- package-lock.json
- package.json
> Updated: oms-api package to latest release(update/oms-version)

- src/services/UtilService.ts
- src/store/modules/order/actions.ts
- src/store/modules/product/actions.ts
- src/store/modules/user/actions.ts
- src/store/modules/util/actions.ts
- src/views/AssignPickerModal.vue
- src/views/Completed.vue
- src/views/InProgress.vue
- src/views/OpenOrders.vue
- src/views/Settings.vue
This reverts commit 1175f7f267f86eaeace139051bd4ef8853f574b1.
Closes #
> Revert "Replaced: throw keyword by Promise.reject(#85zrxrwd7)"

- package-lock.json
- package.json
- release-notes.md
> Updated: app version and release notes for minor release(v1.2.0)

- src/views/Completed.vue
> Implemented: support to print customerLetter and shippingLabel from completed page

- package-lock.json
- package.json
> Updated: app version for minor release (1.3.0)

- src/locales/en.json
- src/views/AssignPickerModal.vue
> Fixed: picklist print issue due to wrong index value being passed and added success toast after picklist is created

- src/store/modules/order/actions.ts
- src/views/InProgress.vue
> Improved: logic to lazy load shipment information for inProgress orders(#85zt3q4xz)

- package-lock.json
- package.json
- release-notes.md
> Updated: app version and release notes for minor release(v1.4.0)

- src/views/Completed.vue
> Fixed: shipmentId should be passed instead of complete shipment list for bulk ship orders (#131)

- package-lock.json
- package.json
> Updated: app version for minor release (1.6.0)

- package-lock.json
- package.json
> Updated: app version for minor release (1.7.0)

- src/store/modules/order/actions.ts
- src/views/Completed.vue
- src/views/InProgress.vue
- src/views/OpenOrders.vue
Closes #139 
- Defined methods to clear the query for specific pages
- Made calls to the defined method from specific pages in the unmounted hook
After:
https://github.com/hotwax/fulfillment-pwa/assets/41404838/3ecd55d7-295d-457e-9630-ac885d670897
> Improved: support to clear the search and selections when changing the page(139)

- src/locales/es.json
Closes #166 
In the es.json file, wrong quotes being used those were causing issue while reading es.json file, so used the correct quotes in es.json
> Fixed: issue of page information being unavailable on refresh by removing the usage of wrong quotes in es.json file(#166)

- src/services/UtilService.ts
- src/store/modules/order/actions.ts
- src/views/InProgress.vue
> Fixed: issue of shipmentId not found on items, and improved logic to create unique key when fetching shipment and shipment route information(#155)

- src/store/modules/util/actions.ts
- src/views/InProgress.vue
> Fixed: issue of order not getting rejected from the inProgress page(#179)

- src/views/AssignPickerModal.vue
> Implemented: support to print picklist after creation from open order page

- src/utils/index.ts
> Improved: the position for the toast to move all the toast messages to bottom

- src/views/InProgress.vue
Closes #201 
When changing the box for an item, the information on the app level is not getting updated resulting in wrong behaviour when changing the box more than twice, so fetched the information for order shipment after updating the package and then updating the shipment information on items.
> Fixed: issue related shipment id when changing the boxes frequently for an item(#201)

- src/components/Menu.vue
> Fixed: menu not enabled when on saved mappings page

- src/components/CreateMappingModal.vue
- src/store/modules/user/actions.ts
> Fixed: issue of mapping not fetched after login

- src/views/InProgress.vue
Closes #187
Implemented: wrapped box chips with ion-label
**Before --** 
**After -** 
> Fixed: Box chips Distortion when Adding More Than 6 Boxes

- package-lock.json
- package.json
> Updated: app version for minor release (1.10.0)

- src/components/Menu.vue
- src/views/Completed.vue
- src/views/InProgress.vue
- src/views/OpenOrders.vue
- src/views/Settings.vue
Related to https://github.com/hotwax/fulfillment-pwa/pull/265
> Fixed: issue of facility name not visible in menu and error messages

- src/components/CreateMappingModal.vue
- src/locales/en.json
- src/locales/es.json
- src/utils/index.ts
- src/views/DownloadPackedOrders.vue
- src/views/UploadImportOrders.vue
Closes #269 
Updated UI:
Selected Fields and custom field:
Reordered fields:
> Implemented: support to reorder fields after selection and updated the UI on the export page

- package-lock.json
- package.json
- src/views/Settings.vue
- vue.config.js
Related Issue: https://github.com/hotwax/dxp-components/issues/177
Used the centralized oms instance navigator on the settings page which is implemented in dxp-components.
> Implemented: centralized oms instance navigator in settings page from dxp-components (#177)

- package-lock.json
- package.json
> Updated: package and lock file for minor release(v1.11.0)

- package-lock.json
- package.json
Closes #
Updated: Version for hot fix rleease release (1.13.1)
> Updated: Version for hot fix rleease release (1.13.1)

- src/store/modules/user/actions.ts
> Implemented: wrap the logout api call in try catch in logout action

- package-lock.json
- package.json
> Updated: package lock and package file for minor release(v1.14.0)

- package-lock.json
- package.json
> Fixed: login halt due to missing user locale by updating DXP version (#308)

- src/store/modules/order/actions.ts
- src/views/ShippingDetails.vue
> Fixed: issue in shipping address data on initial fetch related to undefined and updated the actions to update state in sync(#313)

- src/store/modules/order/actions.ts
> Fixed: issue of shipGroup information(#313)

- src/store/modules/order/actions.ts
- src/utils/order.ts
- src/views/OpenOrders.vue
Closes #313
- Added support to display the status for additional shipments for the order
> Fixed: issue related to wrong status on related shipGroups for order(#313)

- src/views/OrderDetail.vue
> Improved: support to pass shipGroup id when moving to inProgress page(#311)

- package-lock.json
- package.json
Closes #
Updated: package.json and package-lock.json for the minor release.
> Updated: package.json and package-lock.json for the minor release.

- package-lock.json
- package.json
> Improved: app version in package and lock file for minor release(v1.17.0)

- package-lock.json
- package.json
> Improved: app version in package and lock file for patch release(v1.17.1)

- package-lock.json
- package.json
> Improved: app version in package and lock file for patch release(v1.17.2)

- src/views/OrderDetail.vue
> Implemented: support to display the warning for payment chip when not payment is not received(#349)

- src/views/OrderDetail.vue
> Removed: warning color from payment authorized chip

- src/views/Completed.vue
- src/views/OrderDetail.vue
> Fixed: ship button logic by checking tracking code

- package-lock.json
- package.json
> Improved: app version in package and lock file for minor release(v1.19.0)

- package-lock.json
- package.json
Closes #
Updated: app version for the minor release (1.20.0)
> Updated: app version for the minor release (1.20.0)

- package-lock.json
- package.json
Closes #
Updated: app version for the minor release (1.21.0).
> Updated: app version for the minor release (1.21.0).

- src/views/DownloadPackedOrders.vue
> Fixed: case when packed order csv has empty value for a column

- src/store/modules/order/actions.ts
Closes #391
Improved code of completed orders page to show not shipped orders on the top.
> Improved: order status by sorting in completed orders (#391)

- package-lock.json
- package.json
> Updated: app version for minor release(1.22.0)

- src/views/InProgress.vue
> Fixed: Displaying Full Name for Single Assigned Picker in Picklist(#279)

- src/store/modules/util/actions.ts
> Fixed: Display No Variance Rejection Reasons for Order Items(#292)

- src/store/modules/user/actions.ts
> Fixed: code to remove duplicate permission ids passed in the API request.

- package-lock.json
- package.json
> Improved: app version in package and lock file for minor release(v1.23.0)

- src/components/EditPickersModal.vue
- src/views/AssignPickerModal.vue
> Fixed: groupName not being displayed in select picker modal(#409)

- src/components/TransferShipmentActionsPopover.vue
- src/views/TransferShipmentReview.vue
…
Closes #
Fixed: Displayed Generate shipping label button and shipment action popover correctly. (#235)
> Fixed: Displayed Generate shipping label button and shipment action popover correctly. (#235)

- package-lock.json
- package.json
Closes #
Updated: app version for the major release (2.0.0).
> Updated: app version for the major release (2.0.0).

- package-lock.json
- package.json
Closes #
Updated: app version for patch release (2.0.1).
> Updated: app version for patch release (2.0.1).

- src/locales/es.json
Closes #446 
Changed the Spanish text for "Gateway" on the order details page.
> Implemented: Fixed translation error of 'Gateway' to Spanish on the order details page(#446)

- src/views/TransferShipmentReview.vue
Related issue  #431 
Added css to ion content to remove the overlapping of icon and text to have better user experience.
Before:
After : 
> Fixed: code by adding css to ion-content to remove the overlapping of icon and text(#431)

- package-lock.json
- package.json
Closes #
Updated: app version for patch release (2.0.3).
> Updated: app version for patch release (2.0.3).

- src/views/Settings.vue
Related Issue #468
Added the disabled attribute to the ion-item so as to avoid click event on the ion-toggle.
> FIxed: click event triggering even when toggle is disabled (#468)

- src/locales/en.json
- src/locales/es.json
- src/views/RejectionReasons.vue
Related Issue #469
Removed the searching over the rejection reasons.
Before 
After
> Reverted: searching on the rejection reasons page (#469)

- src/views/Completed.vue
- src/views/InProgress.vue
- src/views/OpenOrders.vue
- src/views/TransferOrders.vue
Related Issue #472
Added unique id to all the ion-menu in different page to fix menu referencing issue in case of multiple ion-menu.
> Fixed: multiple menu opening issue by giving unique id to each menu (#472)

- package-lock.json
- package.json
> Updated: app version for the minor release (v2.1.0)

- src/components/CreateRejectionReasonModal.vue
- src/components/EditRejectionReasonModal.vue
- src/locales/en.json
- src/locales/es.json
Related Issue #485
- Made rejection reason name a mandatory field while creation and updation of rejection reason.
> Improved: made rejection reason name a mandatory field (#485)

- src/components/RejectReasonActionsPopver.vue
Related Issue #481
Improved code to show enumName in popover if availabe or else show description.
Before 
After
> Improved: code to show reason name if available in rejection reason popover(#481)

- package-lock.json
- package.json
> Updated: app version for the patch release (v2.1.1)

- package-lock.json
- package.json
Closes #
Updated: app version for minor release (v2.2.0).
> Updated: app version for minor release (v2.2.0).

- package-lock.json
- package.json
> Improved: app version in package and lock file for minor release(v2.4.0)

- src/components/OrderLookupFilters.vue
> Fixed: issue of contentId not being passed(#518)

- src/store/modules/carrier/actions.ts
Closes #
Fixed: Removed unnecessary deep cloning which is causing error. (#493)
> Fixed: Removed unnecessary deep cloning which is causing error. (#493)

- package-lock.json
- package.json
> Improved: app version in package and lock file for patch release(v2.4.1)

- src/components/OrderLookupFilters.vue
- src/store/modules/orderLookup/actions.ts
- src/store/modules/orderLookup/mutations.ts
- src/utils/solrHelper.ts
- src/views/OrderLookup.vue
> Fixed: translate error on console on infinite scroll(#518)

- src/components/CreateShipmentMethodModal.vue
- src/components/EditShipmentMethodSequenceModal.vue
- src/components/ShipmentMethodActionsPopover.vue
- src/locales/en.json
- src/locales/es.json
- src/views/CarrierDetail.vue
- src/views/Carriers.vue
Closes #
Miscellaneous fixes in carrier and shipment methods functionality (#493)
> Miscellaneous fixes in carrier and shipment methods functionality (#493)

- src/components/ShipmentMethods.vue
Closes #
Improved: Formatting changes only (#493).
> Improved: Formatting changes only (#493).

- src/components/ShipmentMethods.vue
Closes #
Fixed: Carrier shipment method association/dissociation functionality when 'Only carrier methods' option is selected. (#493)
> Fixed: Carrier shipment method association/dissociation functionality when 'Only carrier methods' option is selected. (#493)

- src/components/OrderLookupFilters.vue
- src/views/OrderLookup.vue
> Fixed: infinite scroll issue in orderLookup and added support min max values in date selector(#518)

- src/components/OrderLookupFilters.vue
- src/locales/es.json
- src/views/OrderLookup.vue
> Improved: UI to honor internationalization

- src/components/ShipmentMethodActionsPopover.vue
- src/components/ShipmentMethods.vue
- src/store/modules/carrier/actions.ts
- src/views/CarrierDetail.vue
- src/views/Carriers.vue
- src/views/CreateCarrier.vue
Closes #
Fixed: Miscellaneous issues in carrier and shipment methods UI (#493).
> Fixed: Miscellaneous issues in carrier and shipment methods UI (#493).

- package-lock.json
- package.json
Closes #
Updated: app version for the patch release (v2.4.2)
> Updated: app version for the patch release (v2.4.2)

- src/components/Menu.vue
Closes #
Improved rejection reason page permission to hide menu item if not having permission.
> Improved: add permission on menu item of rejection reason

- src/components/ShipmentMethods.vue
- src/views/CarrierDetail.vue
Closes #
Improved: Removed cursor pointer as the item is not clickable (#493).
> Improved: Removed cursor pointer as the item is not clickable (#493).

- src/store/modules/carrier/actions.ts
Closes #
Improved: Updated the view entity name used to fetch the carrier detail as the entity get renamed (#493).
> Improved: Updated the view entity name used to fetch the carrier detail as the entity get renamed (#493).

- .gitignore
> Improved: gitignore file to exclude firebase file from tracking

- src/locales/es.json
- src/store/modules/orderLookup/actions.ts
- src/views/OrderLookupDetail.vue
Closes #
Improved code formatting for order lookup details page and fixed a UI issue
Updated the entry for static text in es.json file
> Fixed: issue in fetching shipGroup information by updating the passed viewSize

- src/components/CreateShipmentMethodModal.vue
- src/components/ShipmentMethodActionsPopover.vue
- src/components/ShipmentMethods.vue
- src/locales/en.json
- src/locales/es.json
- src/store/modules/carrier/actions.ts
- src/utils/index.ts
- src/views/CarrierDetail.vue
Closes #
Fixed: miscellaneous fixes in carrier and shipment methods UI.
> Fixed: miscellaneous fixes in carrier and shipment methods UI

- src/views/OrderLookup.vue
> Implemented: support to remove orderLookup filters when changing the route

- src/store/modules/orderLookup/actions.ts
- src/views/OrderLookupDetail.vue
> Fixed case where lastName is missing for the party

- package-lock.json
- package.json
Closes #
Updated: app version for the patch release v2.4.3
> Updated: app version for the patch release v2.4.3

- src/components/ShipmentMethodActionsPopover.vue
Closes #
Fixed: shipment method name should not be empty while editing (#493).
> Fixed: shipment method name should not be empty while editing (#493).
